[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
clib = { path = "./clib" }
daus = { path = "./daus" }
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower-http = {version = "0.5", features = ["fs"]}
